import {
  faShoppingCart,
  faMagnifyingGlass,
  faCirclePlus,
  faCircleMinus,
  faTrash,
  faStar,
  faStarHalfAlt,
  faAngleLeft,
  faAngleRight,
  faUser,
  faPenToSquare,
  faEye,
  faEyeSlash,
} from '@fortawesome/free-solid-svg-icons';
export const iconsList = [
  faShoppingCart,
  faMagnifyingGlass,
  faCirclePlus,
  faCircleMinus,
  faTrash,
  faStar,
  faStarHalfAlt,
  faAngleLeft,
  faUser,
  faAngleRight,
  faPenToSquare,
  faEye,
  faEyeSlash,
];
